version: '3.8'

services:
  face-emotion-app:
    build: .
    image: face-emotion-app
    container_name: face-emotion-app
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped